name: Run markdown lint
on: push
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm install remark-cli remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent --frail
